### ISSUE TITLE
Rename plugin and move to core Archi code

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-portico-plugin#5]
Once we're done here we can move this to the main Archi code.

Suggestions for the plug-in name please!

```com.archimatetool.importer
com.archimatetool.modelimporter
com.archimatetool.merge
com.archimatetool.importmerge
com.archimatetool.??????
```

**Comment by Phillipus** [comment]
`com.archimatetool.import.model` ?

**Comment by jbsarrodie** [comment]
I think what we do is best described by "a merge of two models" because of the "update" mode. But from the user point of view, as the target model needs first to be open to be able to import the other one inside, I would go for something that convey the "import model" idea.

So `com.archimatetool.modelimporter` seems more suited.

>com.archimatetool.import.model ?

This would be ideal, but only if CSV import is also renamed so that at the end we have:
````
com.archimatetool.import.model
com.archimatetool.import.csv
...
````

Maybe not worth it.

**Comment by Phillipus** [comment]
Everything has been renamed to use `*.modelimporter.*` instead of `*.portico.*` (except this GitHub repo).

I'm afraid you'll have to close the old `*.portico.*` projects in Eclipse and import the new `*.modelimporter.*` ones and set things up in your Run/Debug configuration.

**Comment by Phillipus** [comment]
So, we can continue to test and finalise here in this separate space and when ready the following two projects will become part of main Archi code and added to the `com.archimatetool.editor.feature` Feature project:

```
com.archimatetool.modelimporter
com.archimatetool.modelimporter.commandline
```

The tests project `com.archimatetool.modelimporter.tests` will be added to the tests feature and directory.

**Comment by Phillipus** [comment]
I've now moved these projects to the main Archi code in a branch named `model-importer`.

We can use the `model-importer` branch for a little while in case there are further changes.

@jbsarrodie you'll need to:

1. Remove the portico projects and its git repo from your Eclipse setup
1. Fetch the `model-importer` branch from main Archi git repo and either check it out or merge locally into your master branch
1. Import these projects into Eclipse:
   ```
   com.archimatetool.modelimporter
   com.archimatetool.modelimporter.commandline
   com.archimatetool.modelimporter.tests
   ```
Obviously no more code will be pushed to this repo and I'll archive it at some point. We could continue to use the issue tracker here, though, in case of any more issues arising.

**Comment by Phillipus** [comment]
Now merged into `master` in main Archi code.
